/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videogame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rakshith
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);

        jPanel1.setBackground(new java.awt.Color(147, 147, 200));
        jPanel1.setForeground(new java.awt.Color(217, 21, 21));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jLabel1.setText("cust_id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 75, -1, -1));

        jLabel2.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jLabel2.setText("cust_name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jLabel3.setText("phone_no");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        jLabel4.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jLabel4.setText("cust_email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 202, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 70, 143, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 123, 143, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 159, 144, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 197, 144, -1));

        jTable1.setBackground(new java.awt.Color(155, 155, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cust_id", "cust_name", "phone_no", "cust_email", "card_no"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 12, -1, 275));

        jButton1.setBackground(new java.awt.Color(147, 147, 247));
        jButton1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(217, 21, 21));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 295, -1, -1));

        jButton2.setBackground(new java.awt.Color(147, 147, 247));
        jButton2.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(217, 21, 21));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 295, -1, -1));

        jButton3.setBackground(new java.awt.Color(147, 147, 247));
        jButton3.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(217, 21, 21));
        jButton3.setText("SELECT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 295, -1, -1));

        jButton4.setBackground(new java.awt.Color(147, 147, 247));
        jButton4.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(217, 21, 21));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 295, -1, -1));

        jButton5.setBackground(new java.awt.Color(147, 147, 247));
        jButton5.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(217, 21, 21));
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 295, -1, -1));

        jScrollPane2.setViewportView(jScrollBar1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 0, -1, 348));

        jLabel5.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jLabel5.setText("card_no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, -1, -1));

        jTextField5.setText(" ");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 235, 144, -1));

        jButton6.setBackground(new java.awt.Color(147, 147, 247));
        jButton6.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(210, 28, 28));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 293, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String sql="delete from customer where cust_id=?;";
        try{  
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/videogame","root","RK1234");  
		PreparedStatement pstmt=con.prepareStatement(sql);  
                pstmt.setString(1,jTextField1.getText());
                int x=pstmt.executeUpdate();  
                if(x>=1)
		System.out.println("deletion successful");  
                JOptionPane.showMessageDialog(null,"delete successful","show msg",JOptionPane.PLAIN_MESSAGE);
		con.close();  
		}catch(Exception e){ System.out.println(e);}  
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String sql="insert into customer values(?,?,?,?,?);";
        try{  
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/videogame","root","RK1234");  
		PreparedStatement pstmt=con.prepareStatement(sql);  
                pstmt.setInt(1,Integer.parseInt(jTextField1.getText()));
                pstmt.setString(2,jTextField2.getText());
                pstmt.setString(3,jTextField3.getText());
                pstmt.setString(4,jTextField4.getText());
                pstmt.setString(5,jTextField5.getText());
		pstmt.executeUpdate();  
                //if(x==1)
		//System.out.println("insertion successful");  
                JOptionPane.showMessageDialog(null,"insertion successful","show msg",JOptionPane.PLAIN_MESSAGE);
		con.close();  
		}catch(Exception e){ System.out.println(e);}  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
       tb1Model.setRowCount(0);
        try{  
	Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/videogame","root","RK1234");  
		 
		Statement stmt=con.createStatement();  
		ResultSet rs=stmt.executeQuery("select * from customer"); 
              	while(rs.next())
                {
		String cust_id=rs.getString(1);
                String cust_name=rs.getString(2);
                String cust_email=rs.getString(3);
                String phone_no=rs.getString(4);
                String card_no=rs.getString(5);
                String record[]={cust_id,cust_name,cust_email,phone_no,card_no};
                tb1Model.addRow(record);
                }
                JOptionPane.showMessageDialog(null,"view successful","show msg",JOptionPane.PLAIN_MESSAGE);
		con.close();  
		}catch(Exception e){ System.out.println(e);}
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String sql="update customer set cust_name=?,phone_no=?,cus_email=?,card_no=? where cust_id=?;";
        try{  
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/videogame","root","RK1234");  
		PreparedStatement pstmt=con.prepareStatement(sql); 
                pstmt.setString(1,jTextField2.getText());
                pstmt.setString(2,jTextField3.getText());
                pstmt.setString(3,jTextField4.getText());
                pstmt.setString(4,jTextField5.getText());
                pstmt.setString(5,jTextField1.getText());
		int x=pstmt.executeUpdate();  
                if(x==1)
		System.out.println("Updation successful");  
                JOptionPane.showMessageDialog(null,"update successful","show msg",JOptionPane.PLAIN_MESSAGE);
		con.close();  
		}catch(Exception e){ System.out.println(e);}

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         new options().setVisible(true);
          setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
      
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
